name: SA_Btree
channels:
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2026.5.14
  - ld_impl_linux-64=2.44
  - libexpat=2.8.1
  - libffi=3.4.8
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.6
  - packaging=26.0
  - pip=26.1.1
  - pthread-stubs=0.3
  - python=3.11.15
  - readline=8.3
  - setuptools=82.0.1
  - sqlite=3.51.2
  - tk=8.6.15
  - tzdata=2026b
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.8.2
  - zlib=1.3.1
  - pip:
      - certifi==2026.5.20
      - charset-normalizer==3.4.7
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.63.0
      - idna==3.18
      - kiwisolver==1.5.0
      - matplotlib==3.10.9
      - numpy==2.4.6
      - pandas==3.0.3
      - pillow==12.2.0
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - requests==2.34.2
      - six==1.17.0
      - urllib3==2.7.0
